######################
# Threads to use
######################
THREADS: 50

######################
# SQLITE Database
######################
SQLITE: 'harvested.sqlite'

######################
# Slack api tokens
######################
SLACK_API: ''

######################
# SMTP information
######################
SMTP:
    port: 8000
    username: johndoe
    host: myhost.com
    password: 1234
    tls: true

######################
# Github api tokens
######################
GITHUB_TOKENS:
  - "1234"
  - "1234"

######################
# File whitelists etc
######################
FILE_BLACKLIST:
  - .txt

######################
# metadata to find
######################
    # Find API.txt files for debug
    -   name: 'api.txt File'
        type: 'filename'
        match: 'api.txt'

    # Find .env files
    -   name: '.env File'
        type: 'extension'
        match: '.env'

    # Find .conf files
    -   name: '.conf File'
        type: 'extension'
        match: '.conf'

    # Find twitter api key
    -   name: 'Twitter Api Key'
        type: 'contents'
        match:
            - 'twitter_api_key=(.*?)'
            - 'twitter_api_key="(.*?)"'
            - 'twitterapikey="(.*?)"'
            - 'twitterapikey=(.*?)'
            - 'twitter-api-key=(.*?)'
            - 'twitter-api-key="(.*?)"'
            - 'twitter_api_key:(.*?)'
            - 'twitter_api_key:"(.*?)"'
            - 'twitterapikey:"(.*?)"'
            - 'twitterapikey:(.*?)'
            - 'twitter-api-key:(.*?)'
            - 'twitter-api-key:"(.*?)"'
            - 'twitter_api_key = (.*?)'
            - 'twitter_api_key = "(.*?)"'
            - 'twitterapikey = "(.*?)"'
            - 'twitterapikey = (.*?)'
            - 'twitter-api-key = (.*?)'
            - 'twitter-api-key = "(.*?)"'
            - 'twitter_api_key: (.*?)'
            - 'twitter_api_key: "(.*?)"'
            - 'twitterapikey: "(.*?)"'
            - 'twitterapikey: (.*?)'
            - 'twitter-api-key: (.*?)'
            - 'twitter-api-key: "(.*?)"'

    # Find twitter api secret
    -   name: 'Twitter Api Secret'
        type: 'contents'
        match:
            - 'twitter_api_secret=(.*?)'
            - 'twitter_api_secret="(.*?)"'
            - 'twitterapisecret="(.*?)"'
            - 'twitterapisecret=(.*?)'
            - 'twitter-api-secret=(.*?)'
            - 'twitter-api-secret="(.*?)"'
            - 'twitter_api_secret:(.*?)'
            - 'twitter_api_secret:"(.*?)"'
            - 'twitterapisecret:"(.*?)"'
            - 'twitterapisecret:(.*?)'
            - 'twitter-api-secret:(.*?)'
            - 'twitter-api-secret:"(.*?)"'
            - 'twitter_api_secret = (.*?)'
            - 'twitter_api_secret = "(.*?)"'
            - 'twitterapisecret = "(.*?)"'
            - 'twitterapisecret = (.*?)'
            - 'twitter-api-secret = (.*?)'
            - 'twitter-api-secret = "(.*?)"'
            - 'twitter_api_secret: (.*?)'
            - 'twitter_api_secret: "(.*?)"'
            - 'twitterapisecret: "(.*?)"'
            - 'twitterapisecret: (.*?)'
            - 'twitter-api-secret: (.*?)'
            - 'twitter-api-secret: "(.*?)"'